'use client'
import { useEffect, useState } from 'react';
import './globals.css'
import { Inter } from 'next/font/google'
import Login from './login/page';
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 const [token, setToken] = useState(null)
 const router = useRouter();
 

 useEffect(() => {
    const getToken = localStorage.getItem('access_token');
    setToken(getToken)
    if(!token) {
      router.push("/login")
    }
  }, [token]);
  

  return (
    <html lang="en">
      <body className=''>{children}</body>
    </html>
  )
}
